{
  "composition.field.add": "Tilføj et felt",
  "composition.field.deleteConfirmation": "Er du sikker på, at du vil slette dette felt?",
  "composition.field.core.campaignmonitor": "Nyhedsbrevs-tilmelding",
  "composition.field.core.checkbox": "Checkbox",
  "composition.field.core.checkboxgroup": "Checkbox-gruppe",
  "composition.field.core.date": "Dato-vælger",
  "composition.field.core.dropdown": "Rulleboks",
  "composition.field.core.email": "E-mailadresse",
  "composition.field.core.heading": "Overskrift",
  "composition.field.core.image": "Billede",
  "composition.field.core.link": "Link",
  "composition.field.core.mailchimp": "Nyhedsbrevs-tilmelding",
  "composition.field.core.memberinfo": "Medlems-information",
  "composition.field.core.number": "Heltal",
  "composition.field.core.radiobuttongroup": "Radioknapper",
  "composition.field.core.recaptcha": "Spambeskyttelse (reCAPTCHA)",
  "composition.field.core.selectbox": "Multivælger",
  "composition.field.core.submitbutton": "Gem-knap",
  "composition.field.core.textarea": "Tekstfelt",
  "composition.field.core.textbox": "Tekstboks",
  "composition.field.core.textParagraph": "Tekst",
  "composition.field.core.upload": "Fil-upload",
  "composition.field.core.url": "Web-adresse",
  "composition.header": "Formular-layout",
  "composition.pages.add": "Tilføj en side",
  "composition.pages.empty": "Klik her for at tilføje en side",
  "composition.pages.header": "Side nr. ",
  "composition.pick.field.header": "Tilføj et felt",
  "composition.pick.field.text": "Vælg hvilken type felt der skal tilføjes.",
  "composition.pick.row.header": "Tilføj en række",  
  "composition.pick.row.text": "Vælg hvilken type række der skal tilføjes.",  
  "composition.row.add": "Tilføj en række",
  "composition.row.deleteConfirmation": "Er du sikker på, at du vil slette denne række?",
  "composition.row.one-column": "Enkelt kolonne",
  "composition.row.two-column": "To kolonner",
  "composition.row.two-column-wide-left": "To kolonner (bred venstre-kolonne)",
  "composition.row.two-column-wide-right": "To kolonner (bred højre-kolonne)",
  "composition.row.three-column": "Tre kolonner",
  "composition.rows.empty": "Klik her for at tilføje en række",
  "composition.text": "Du sætter din formular op ved at tilføje rækker og felter nedenfor. Hvis du senere hen får brug for at ændre på opsætningen, kan både rækker og felter flyttes rundt ved at trække i dem.",

  "validation.add": "Tilføj en validering",
  "validation.condition.core.fieldisempty": "Feltet er tomt",
  "validation.condition.core.fieldisnotempty": "Feltet er ikke tomt",
  "validation.condition.core.fieldvalueis": "Værdien er",
  "validation.condition.core.fieldvalueisnot": "Værdien er ikke",
  "validation.condition.core.fieldvaluesdonotmatch": "Værdien matcher ikke et andet felt",
  "validation.condition.core.fieldvaluesmatch": "Værdien matcher et andet felt",
  "validation.errorMessage.header": "...skal denne fejlbesked vises:",
  "validation.header": "Validering",
  "validation.pick.field": "Vælg et felt:",
  "validation.pick.condition": "Vælg en betingelse:",
  "validation.rules.fieldHeader": "Felt",
  "validation.rules.conditionHeader": "Betingelse",
  "validation.rules.add": "Tilføj en regel",
  "validation.rules.add.header": "Tilføj en regel",
  "validation.rules.add.text": "En regel består af et felt og en betingelse. Hvis feltets værdi opfylder betingelsen, er reglen opfyldt.",
  "validation.rules.header": "Hvis disse regler er opfyldt...",
  "validation.text": "Her kan du sætte valideringer op, der går på tværs af de enkelte felter i formularen - f.eks. \"formularen er ugyldig hvis felt A er tomt og felt B ikke er tomt\".",
  "validation.text.noFields": "Du skal tilføje felter til formularen, før du kan sætte validering op.",

  "actions.header": "Handlinger",
  "actions.text": "Her kan du oprette handlinger, der viser eller skjuler felter baseret på andre felters værdi - f.eks. \"vis kun felt A hvis felt B ikke er tomt\".",
  "action.task.header": "...skal denne handling udføres:",
  "action.task.theField": "feltet",
  "action.task.showField": "Vis",
  "action.task.hideField": "Skjul",
  "action.add": "Tilføj en handling",
  "action.text.noFields": "Du skal tilføje felter til formularen, før du kan oprette handlinger.",

  "email.submittedValues.helpText": "Du kan inkludere værdierne af felterne i den indsendte formular. Hvis du for eksempel har en tekstboks med navnet \"Navn\", kan du inkludere dennes indsendte værdi ved at tilføje \"[Navn]\".",

  "emailConfirmation.header": "E-mailbekræftelse",
  "emailConfirmation.text": "Hvis du vil sende en e-mailbekræftelse til brugerne, når de har udfyldt formularen, skal du vælge det felt, der underholder modtagerens e-mailadresse og indtaste e-mailens emnetekst og afsenderens e-mailadresse.",
  "emailConfirmation.recipientsField": "E-mailadresse-felt",
  "emailConfirmation.subject": "Emnetekst",
  "emailConfirmation.body": "Indhold",
  "emailConfirmation.sender": "Afsenderens e-mailadresse",

  "emailNotification.attachments": "Vedhæft uploadede filer til mailen",
  "emailNotification.attachments.helpText": "Hvis du vælger dette, bør du overveje at begrænse den tilladte fil-størrelse på upload-felterne.",
  "emailNotification.header": "E-mailnotifikation",
  "emailNotification.text": "Hvis du vil have e-mailnotifikation, når brugerne udfylder formularen, skal du indtaste modtagernes e-mailadresser, e-mailens emnetekst og afsenderens e-mailadresse.",
  "emailNotification.recipients": "Modtager-adresser",
  "emailNotification.subject": "Emnetekst",
  "emailNotification.sender": "Afsenderens e-mailadresse",
  
  "receipt.header" : "Kvittering",
  "receipt.page": "Kvitteringsside",
  "receipt.page.header": "Vælg en side",
  "receipt.page.text": "Hvis du vil videresende brugerne til en anden side, når de har udfyldt formularen, kan du vælge denne side nedenfor.",
  "receipt.page.select": "Vælg...",
  "receipt.message.header": "...eller indtast en besked",
  "receipt.message.text": "Hvis du hellere vil vise en besked til brugerne, når de har udfyldt formularen, kan du indtaste denne besked nedenfor.",
  "receipt.message.heading": "Overskrift",
  "receipt.message.body": "Tekst",

  "limitations.header": "Begrænsninger",

  "data.header": "Indsendte data",
  "data.text": "Her kan du se de formular-data, brugerne har indsendt.",
  "data.visibleFields.header": "Vælg viste felter", 
  "data.visibleFields.text": "Vælg de felter, du ønsker vist i tabellen. Hvis du vælger at skjule et eller flere felter, kan du klikke på en række i tabellen for at se alle rækkens felter.", 
  "data.sortSubmittedDate": "Dato",
  "data.pagePrevious": "Forrige",
  "data.pageNext": "Næste",
  "data.exportAllToCsv": "Eksportér til CSV",
  "data.deleteSelected": "Slet valgte",
  "data.loadingData": "Henter formular-data...",
  "data.noData": "Ingen formular-data fundet",
  "data.noSearchResults": "Ingen søgeresultater",
  "data.statistics.header": "Statistik",
  "data.statistics.loadingData": "Henter statistikken...",
  "data.statistics.totalRows": "Total antal:",
  "data.statistics.noStatisticsHeader": "Ingen statistik tilgængelig",
  "data.statistics.noStatisticsText": "Der kan desværre ikke dannes nogen statistik ud fra de indsendte data.",
  "data.statistics.loadingGraph": "Tegner grafen...",
  "data.maxSubmissions": "Antal indsendelser",
  "data.maxSubmissions.header": "Begræns antallet af indsendelser",
  "data.maxSubmissions.text": "Hvis du vil begrænse antallet af indsendelser for denne formular, kan du angive det maksimalt tilladte antal indsendelser herunder og indtaste en besked, der vises til brugerne, hvis dette antal indsendelser overskrides.",
  "data.maxSubmissions.message.heading": "Overskrift",
  "data.maxSubmissions.message.body": "Tekst",
  "data.maxSubmissionsPerUser": "Flere indsendelser",
  "data.maxSubmissionsPerUser.header": "Flere indsendelser per bruger",
  "data.maxSubmissionsPerUser.text": "Hvis du ikke vil have, at den samme bruger indsender denne formular flere gange, kan du sætte kryds herunder og indtaste en besked, der vises til de brugere, der allerede har indsendt formularen.",
  "data.disallowMultipleSubmissionsPerUser": "Kun én indsendelse per bruger",
  "data.maxSubmissionsPerUser.message.heading": "Overskrift",
  "data.maxSubmissionsPerUser.message.body": "Tekst",
  "data.daysBeforeExpiry": "Antal dage før sletning",
  "data.daysBeforeExpiry.helpText": "Indtast det antal dage, de indsendte data skal beholdes, før de slettes automatisk. Lad feltet være tomt hvis indsendelserne ikke skal slettes automatisk.",
  
  "edit.campaignMonitor.nameField": "Felt til navn",  
  "edit.campaignMonitor.nameField.helpText": "Hvilket felt indeholder den tilmeldtes navn?",  
  "edit.checkbox.checked.helpText": "Sæt kryds her hvis feltet skal være valgt som standard",  
  "edit.checked": "Valgt",  
  "edit.close": "Luk",
  "edit.defaultText": "Default-valg", 
  "edit.defaultText.helpText": "F.eks. \"Vælg...\" - hvis denne er tom, vises ingen default-tekst", 
  "edit.edit": "Rediger",
  "edit.email.allowMultiple": "Tillad mere end én",
  "edit.email.allowMultiple.helpText": "Sæt kryds her hvis brugerne skal kunne indtaste mere end én e-mailadresse",
  "edit.errorMessage": "Fejlbesked",
  "edit.errorMessage.helpText": "Beskeden der vises til brugerne, hvis det indtastede data ikke er gyldigt", 
  "edit.header.text.helpText": "Teksten der skal vises i overskriften",
  "edit.helpText": "Hjælpetekst",  
  "edit.helpText.helpText": "Forklarende tekst til at hjælpe brugerne", 
  "edit.image.choose": "Vælg billede",
  "edit.image.choose.helpText": "Klik nedenfor for at vælge et billede",
  "edit.image.caption": "Billedtekst",
  "edit.image.caption.helpText": "Teksten der skal vises til billedet",
  "edit.label": "Tekst",  
  "edit.label.helpText": "Felt-teksten der vises til brugerne", 
  "edit.link.text": "Tekst",
  "edit.link.text.helpText": "Teksten der skal vises som et link",
  "edit.link.target": "Destination",
  "edit.link.target.helpText": "Vælg den side der skal linkes til",
  "edit.link.select": "Vælg...",
  "edit.link.openInNewWindow": "Åbn i et nyt vindue",
  "edit.link.openInNewWindow.helpText": "Sæt kryds her hvis linket skal åbne i et nyt vindue",
  "edit.mandatory": "Påkrævet", 
  "edit.mandatory.helpText": "Sæt kryds her hvis feltet skal være påkrævet", 
  "edit.maxLength": "Max antal karakterer",
  "edit.maxLength.helpText": "Max antal karakterer tilladt i feltet (0 = ubegrænset)",
  "edit.memberInfo.helpText": "Når dette felt er føjet til formularen, bliver navne og e-mailadresser automatisk gemt for de medlemmer, der er logget ind.",
  "edit.name": "Navn",  
  "edit.name.helpText": "Navnet skal være unikt",
  "edit.number.minimum": "Minimum",
  "edit.number.minimum.helpText": "Det laveste tilladte tal",
  "edit.number.maximum": "Maximum",
  "edit.number.maximum.helpText": "Det højeste tilladte tal",
  "edit.ok": "Gem",
  "edit.options": "Valgmuligheder",
  "edit.options.add": "Tilføj en valgmulighed",  
  "edit.options.helpText": "Tilføj de valgmuligheder, brugerne skal kunne vælge imellem",
  "edit.options.selected": "Valgt",  
  "edit.placeholder": "Pladsholder",  
  "edit.placeholder.helpText": "Tekst der vises når feltet ikke er udfyldt", 
  "edit.renameWarning": "Hvis du omdøber et eksisterende felt, vil du ikke længere kunne se de indsendte data for dette felt", 
  "edit.selectbox.multiSelect": "Tillad flere valgte",
  "edit.selectbox.multiSelect.helpText": "Sæt kryds her hvis brugerne skal kunne vælge flere valgmuligheder", 
  "edit.selectbox.size": "Antal viste valgmuligheder",
  "edit.selectbox.size.all": "Alle tilgængelige valgmuligheder", 
  "edit.selectbox.size.helpText": "Der bliver vist en scrollbar, hvis du vælger et antal der er lavere end antallet af tilgængelige valgmuligheder", 
  "edit.submitButton.label": "Knappens tekst",
  "edit.submitButton.label.helpText": "Teksten der vises på knappen - f.eks. \"Gem\" eller \"Indsend\"",
  "edit.text": "Tekst",
  "edit.textParagraph.text.helpText": "Teksten der skal vises i tekstafsnittet",
  "edit.upload.allowedFileTypes": "Tilladte filtyper",
  "edit.upload.allowedFileTypes.helpText": "F.eks. \"JPG, PNG, GIF\"",
  "edit.upload.maxSize": "Max fil-størrelse (KB)",
  "edit.upload.maxSize.helpText": "0 = ubegrænset",
  
  "common.clickToExpand": "klik for at folde ud"
}