{
  "composition.field.add": "Tilføj et felt",
  "composition.field.deleteConfirmation": "Er du sikker på, at du vil slette dette felt?",
  "composition.field.core.checkbox": "Checkbox",
  "composition.field.core.checkboxgroup": "Checkbox-gruppe",
  "composition.field.core.date": "Dato-vælger",
  "composition.field.core.dropdown": "Rulleboks",
  "composition.field.core.email": "E-mailadresse",
  "composition.field.core.heading": "Overskrift",
  "composition.field.core.image": "Billede",
  "composition.field.core.number": "Heltal",
  "composition.field.core.radiobuttongroup": "Radioknapper",
  "composition.field.core.recaptcha": "Spambeskyttelse (reCAPTCHA)",
  "composition.field.core.selectbox": "Multivælger",
  "composition.field.core.submitbutton": "Gem-knap",
  "composition.field.core.textarea": "Tekstfelt",
  "composition.field.core.textbox": "Tekstboks",
  "composition.field.core.textParagraph": "Tekst",
  "composition.field.core.upload": "Fil-upload",
  "composition.field.core.url": "Web-adresse",
  "composition.header": "Form-layout",
  "composition.pages.add": "Tilføj en side",
  "composition.pages.empty": "Klik her for at tilføje en side",
  "composition.pages.header": "Side nr. ",
  "composition.pick.field.header": "Tilføj et felt",
  "composition.pick.field.text": "Vælg hvilken type felt der skal tilføjes.",
  "composition.pick.row.header": "Tilføj en række",  
  "composition.pick.row.text": "Vælg hvilken type række der skal tilføjes.",  
  "composition.row.add": "Tilføj en række",
  "composition.row.deleteConfirmation": "Er du sikker på, at du vil slette denne række?",
  "composition.row.one-column": "Enkelt kolonne",
  "composition.row.two-column": "To kolonner",
  "composition.row.two-column-wide-left": "To kolonner (bred venstre-kolonne)",
  "composition.row.two-column-wide-right": "To kolonner (bred højre-kolonne)",
  "composition.row.three-column": "Tre kolonner",
  "composition.rows.empty": "Klik her for at tilføje en række",
  "composition.text": "Du sætter din form op ved at tilføje rækker og felter nedenfor. Hvis du senere hen får brug for at ændre på opsætningen, kan både rækker og felter flyttes rundt ved at trække i dem.",

  "validation.add": "Tilføj en validering",
  "validation.condition.core.fieldisempty": "Feltet er tomt",
  "validation.condition.core.fieldisnotempty": "Feltet er ikke tomt",
  "validation.condition.core.fieldvalueis": "Værdien er",
  "validation.condition.core.fieldvalueisnot": "Værdien er ikke",
  "validation.condition.core.fieldvaluesdonotmatch": "Værdien matcher ikke et andet felt",
  "validation.condition.core.fieldvaluesmatch": "Værdien matcher et andet felt",
  "validation.errorMessage": "Fejlbesked",
  "validation.header": "Validering",
  "validation.pick.field": "Vælg et felt:",
  "validation.pick.condition": "Vælg en betingelse:",
  "validation.rules.fieldHeader": "Felt",
  "validation.rules.conditionHeader": "Betingelse",
  "validation.rules.add": "Tilføj en regel",
  "validation.rules.add.header": "Tilføj en regel",
  "validation.rules.add.text": "En regel består af et felt og en betingelse. Hvis feltets værdi opfylder betingelsen, er reglen opfyldt.",
  "validation.text": "Her kan du sætte valideringer op  for hele formen, f.eks. \"hvis felt A er tomt, skal felt B være udfyldt\". En validering består af et sæt regler, der skal opfyldes, samt en fejlbesked der vises, hvis ikke reglerne er opfyldt.",
  "validation.text.noFields": "Du skal tilføje felter til formen, før du kan sætte validering op.",

  "emailConfirmation.header": "E-mailbekræftelse",
  "emailConfirmation.text": "Hvis du vil sende en e-mailbekræftelse til brugerne, når de har udfyldt formen, skal du vælge det felt, der underholder modtagerens e-mailadresse og indtaste e-mailens emnetekst og afsenderens e-mailadresse.",
  "emailConfirmation.recipientsField": "E-mailadresse-felt",
  "emailConfirmation.subject": "Emnetekst",
  "emailConfirmation.sender": "Afsenderens e-mailadresse",
  
  "emailNotification.header": "E-mailnotifikation",
  "emailNotification.text": "Hvis du vil have e-mailnotifikation, når brugerne udfylder formen, skal du indtaste modtagernes e-mailadresser, e-mailens emnetekst og afsenderens e-mailadresse.",
  "emailNotification.recipients": "Modtager-adresser",
  "emailNotification.subject": "Emnetekst",
  "emailNotification.sender": "Afsenderens e-mailadresse",
  
  "receipt.header" : "Kvittering",
  "receipt.page.header": "Vælg en side",
  "receipt.page.text": "Hvis du vil videresende brugerne til en anden side, når de har udfyldt formen, kan du vælge denne side nedenfor.",
  "receipt.page.select": "Vælg...",
  "receipt.message.header": "...eller indtast en besked",
  "receipt.message.text": "Hvis du hellere vil vise en besked til brugerne, når de har udfyldt formen, kan du indtaste denne besked nedenfor.",
  "receipt.message.heading": "Overskrift",
  "receipt.message.body": "Tekst",

  "data.visibleFields.header": "Viste felter", 
  "data.visibleFields.text": "Vælg de felter, du ønsker vist i tabellen nedenfor. Hvis du vælger at skjule et eller flere felter, kan du klikke på en række i tabellen for at se alle rækkens felter.", 
  "data.sortSubmittedDate": "Dato",
  "data.pagePrevious": "Forrige",
  "data.pageNext": "Næste",
  "data.exportAllToCsv": "Eksportér til CSV",
  "data.deleteSelected": "Slet valgte",
  "data.loadingData": "Henter data...",
  "data.noData": "Intet data fundet.",
  
  "edit.checked": "Valgt",  
  "edit.close": "Luk",
  "edit.defaultText": "Default-valg", 
  "edit.defaultText.helpText": "F.eks. \"Vælg...\" - hvis denne er tom, vises ingen default-tekst", 
  "edit.edit": "Rediger",
  "edit.email.allowMultiple": "Tillad mere end én",
  "edit.errorMessage": "Fejlbesked",
  "edit.errorMessage.helpText": "Beskeden der vises til brugerne, hvis det indtastede data ikke er gyldigt", 
  "edit.helpText": "Hjælpetekst",  
  "edit.helpText.helpText": "Forklarende tekst til at hjælpe brugerne", 
  "edit.image.choose": "Vælg billede",
  "edit.image.caption": "Billedtekst",
  "edit.label": "Tekst",  
  "edit.label.helpText": "Felt-teksten der vises til brugerne", 
  "edit.mandatory": "Påkrævet", 
  "edit.mandatory.helpText": "Sæt kryds her hvis feltet skal være påkrævet", 
  "edit.maxLength": "Max antal karakterer",
  "edit.maxLength.helpText": "Max antal karakterer tilladt i feltet (0 = ubegrænset)",
  "edit.name": "Navn",  
  "edit.name.helpText": "Navnet skal være unikt",
  "edit.number.minimum": "Minimum",
  "edit.number.maximum": "Maximum",
  "edit.ok": "Gem",
  "edit.options": "Valgmuligheder",
  "edit.options.add": "Tilføj en valgmulighed",  
  "edit.options.helpText": "Tilføj de valgmuligheder, brugerne skal kunne vælge imellem",
  "edit.options.selected": "Valgt",  
  "edit.placeholder": "Pladsholder",  
  "edit.placeholder.helpText": "Tekst der vises når feltet ikke er udfyldt", 
  "edit.selectbox.multiSelect": "Tillad flere valgte",
  "edit.selectbox.multiSelect.helpText": "Sæt kryds her hvis brugerne skal kunne vælge flere valgmuligheder", 
  "edit.selectbox.size": "Antal viste valgmuligheder",
  "edit.selectbox.size.all": "Alle tilgængelige valgmuligheder", 
  "edit.selectbox.size.helpText": "Der bliver vist en scrollbar, hvis du vælger et antal der er lavere end antallet af tilgængelige valgmuligheder", 
  "edit.submitButton.label": "Tekst på knappen",
  "edit.text": "Tekst",
  "edit.upload.allowedFileTypes": "Tilladte filtyper",
  "edit.upload.allowedFileTypes.helpText": "F.eks. \"JPG, PNG, GIF\"",
  "edit.upload.maxSize": "Max fil-størrelse (KB)",
  "edit.upload.maxSize.helpText": "0 = ubegrænset",
  
  "common.clickToExpand": "klik for at folde ud"
}