{
    "composition.field.add": "Veld toevoegen",
    "composition.field.deleteConfirmation": "Verwijderen. Weet u het zeker?",
    "composition.field.core.campaignmonitor": "Nieuwsbrief-abonnement",
    "composition.field.core.checkbox": "Checkbox",
    "composition.field.core.checkboxgroup": "Checkbox Groep",
    "composition.field.core.consent": "Verzend akkoord",
    "composition.field.core.date": "Datum",
    "composition.field.core.dropdown": "Dropdown",
    "composition.field.core.email": "E-mailadres",
    "composition.field.core.heading": "Titel",
    "composition.field.core.image": "Afbeelding",
    "composition.field.core.link": "Link",
    "composition.field.core.mailchimp": "Nieuwsbrief-abonnement",
    "composition.field.core.memberinfo": "Leden informatie",
    "composition.field.core.number": "Nummer",
    "composition.field.core.radiobuttongroup": "Radio Button Groep",
    "composition.field.core.recaptcha": "Spam beveiliging (reCAPTCHA)",
    "composition.field.core.selectbox": "Keuzelijst",
    "composition.field.core.submitbutton": "Verzend Knop",
    "composition.field.core.telephone": "Telefoonnummer",
    "composition.field.core.textarea": "Tekstveld (meerdere regels)",
    "composition.field.core.textbox": "Tekstveld (1 regel)",
    "composition.field.core.textParagraph": "Tekst Paragraaf",
    "composition.field.core.upload": "Bestand Upload",
    "composition.field.core.url": "Internetadres",
    "composition.header": "Velden",
    "composition.pages.add": "Voeg een pagina toe",
    "composition.pages.empty": "Klik hier om een pagina toe te voegen",
    "composition.pages.header": "Pagina nr. ",
    "composition.pick.field.header": "Veld toevoegen",
    "composition.pick.field.text": "Kies welke veld je wilt plaatsen",
    "composition.pick.row.header": "Voeg een regel toe",  
    "composition.pick.row.text": "Kies het type regel dat je wilt toevoegen.",  
    "composition.row.add": "Nieuwe Regel",
    "composition.row.deleteConfirmation": "Regel verwijderen. Weet je het zeker?",
    "composition.row.one-column": "1 kolom",
    "composition.row.two-column": "2 kolommen",
    "composition.row.two-column-wide-left": "80/20 verhouding",
    "composition.row.two-column-wide-right": "20/80 verhouding",
    "composition.row.three-column": "3 kolommen",
    "composition.rows.empty": "Klik hier om een regel toe te voegen",
    "composition.text": " ",

    "validation.add": "Validatie toevoegen",
    "validation.condition.core.fieldisempty": "Formulier-veld is leeg",
    "validation.condition.core.fieldisnotempty": "Formulier-veld is niet leeg",
    "validation.condition.core.fieldvalueis": "Waarde is",
    "validation.condition.core.fieldvalueisnot": "Waarde is niet",
    "validation.condition.core.fieldvaluesdonotmatch": "Waarde is niet gelijk aan een ander formulier-veld",
    "validation.condition.core.fieldvaluesmatch": "Waarde is gelijk aan een ander formulier-veld",
    "validation.errorMessage.header": "...toon dan deze foutmelding:",
    "validation.header": "Validaties",
    "validation.header.helpText": "Deze tekst wordt getoond boven de foutmeldingen als het formulier niet geldig is.",
    "validation.pick.field": "Kies een formulier-veld:",
    "validation.pick.condition": "Kies een voorwaarde:",
    "validation.rules.fieldHeader": "Formulier-veld",
    "validation.rules.conditionHeader": "Voorwaarde",
    "validation.rules.add": "Regel toevoegen",
    "validation.rules.add.header": "Regel toevoegen",
    "validation.rules.add.text": "Een regel bestaat uit een formulier-veld en een voorwaarde. Als de waarde in het formulier-veld voldoet aan de voorwaarde, dan wordt deze regel toegepast.",
    "validation.rules.header": "Als deze regels zijn voldaan...",
    "validation.text": "Je kunt hier regels instellen. Bijv: \"Het formulier mag pas verzonden worden als veld A leeg is en veld B niet leeg is\".",
    "validation.text.noFields": "Je moet eerst velden toevoegen aan het formulier voordat je validaties kunt toevoegen.",

    "actions.header": "Acties",
    "actions.text": "Met acties kun je formulier-velden tonen of verbergen op basis van waarde in andere velden. Bijv: \"Toon alleen formulier-veld A als formulier-veld B niet leeg is\".",
    "action.task.header": "...voer dan deze actie uit:",
    "action.task.theField": "het veld",
    "action.task.showField": "Toon",
    "action.task.hideField": "Verberg",
    "action.add": "Voeg een actie toe",
    "action.text.noFields": "Je moet velden aan het formulier toevoegen voordat u acties kunt maken.",

    "email.submittedValues.helpText": "Voeg de waarde uit een veld toe door de veldnaam te noemen tussen haakjes. Bijv. [Voornaam]",
    
    "emails.header": "E-mail",
    
    "emailConfirmation.header": "E-mailbevestiging naar Bezoeker",
    "emailConfirmation.text": " ",
    "emailConfirmation.recipientsField": "E-mailadres veld",
    "emailConfirmation.subject": "Onderwerp",
    "emailConfirmation.body": "Inhoud",
    "emailConfirmation.sender": "E-mailadres afzender",

    "emailNotification.attachments": "Zend ook bijlagen mee",
    "emailNotification.attachments.helpText": "Als je een upload-veld in je formulier hebt, dan kun je ook dit bestand, van de bezoeker, mee laten zenden.",
    "emailNotification.header": "E-mailbevestiging naar Beheerder",
    "emailNotification.text": " ",
    "emailNotification.recipients": "E-mailadres beheerder",
    "emailNotification.subject": "Onderwerp",
    "emailNotification.sender": "E-mailadres afzender",
  
    "receipt.header" : "Afhandeling",
    "receipt.page": "Bestemmingspagina",
    "receipt.page.header": "Pagina selecteren",
    "receipt.page.text": "Als je wilt dat de bezoeker wordt doorgestuurd naar een andere pagina, selecteer hieronder dan deze pagina.",
    "receipt.page.select": "Kies...",
    "receipt.message.header": "...of voer een bericht in",
    "receipt.message.text": "Als je liever hebt dat de bezoeker een bericht ziet nadat deze het formulier heeft verzonden, typ dan hieronder het bericht.",
    "receipt.message.heading": "Titel",
    "receipt.message.body": "Tekst",

    "limitations.header": "Beperkingen",

    "data.header": "Reacties",
    "data.text": "De reacties staan in de tabel hieronder.",
    "data.visibleFields.header": "Kies welke velden getoond moeten worden", 
    "data.visibleFields.text": "Selecteer de formulier-velden die je wilt tonen in de tabel. Als je er voor kiest om één of meerdere velden te verbergen, dan kun je alsnog alle velden zien als je in de tabel op de pijltjes in de betreffende regel klikt.", 
    "data.sortSubmittedDate": "Datum",
    "data.pagePrevious": "Vorige",
    "data.pageNext": "Volgende",
    "data.exportAllToCsv": "Exporteren naar CSV",
    "data.deleteSelected": "Verwijder de geselecteerde items",
    "data.loadingData": "Bezig met laden van ingevulde formulieren...",
    "data.noData": "Er zijn (nog) geen ingevulde formulieren",
    "data.noSearchResults": "Geen resulaten gevonden",
    "data.viewEntry.header": "Alle velden van dit formulier",
    "data.statistics.header": "Statistieken",
    "data.statistics.loadingData": "Bezig met laden van statistieken...",
    "data.statistics.totalRows": "Total aantal:",
    "data.statistics.noStatisticsHeader": "Geen statistieken beschikbaar",
    "data.statistics.noStatisticsText": "Helaas kunnen er geen statistieken worden gegenereerd op basis van de beschikbare gegevens.",
    "data.statistics.loadingGraph": "Bezig met genereren van de grafiek...",
    "data.maxSubmissions": "Aantal ingevulde formulieren",
    "data.maxSubmissions.header": "Beperk het aantal ingevulde formulierem",
    "data.maxSubmissions.text": "Als u het aantal ingevulde formulieren wilt beperken, dan kunt u het maximaal toegestane aantal hieronder opgeven. Ook kunt u een bericht invoeren dat wordt weergegeven aan de bezoeker als het aantal is overschreden.",
    "data.maxSubmissions.message.heading": "Opschrift",
    "data.maxSubmissions.message.body": "Tekst",
    "data.maxSubmissionsPerUser": "Meer ingevulde formulieren",
    "data.maxSubmissionsPerUser.header": "Meerdere ingevulde formulieren per gebruiker",
    "data.maxSubmissionsPerUser.text": "Als u niet wilt dat dezelfde bezoeker het formulier meerdere keren verzend, dan vinkt u dat hieronder aan en typt u een bericht die de bezoeker te zien krijgt.",
    "data.disallowMultipleSubmissionsPerUser": "Maximaal 1 ingevuld formulier toestaan per bezoeker",
    "data.maxSubmissionsPerUser.message.heading": "Opschrift",
    "data.maxSubmissionsPerUser.message.body": "Tekst",
    "data.daysBeforeExpiry": "Hoe lang bewaren? (in dagen)",
    "data.daysBeforeExpiry.helpText": "Voer het aantal dagen in dat de ingediende gegevens moet worden bewaard voordat ze automatisch worden verwijderd. Laat het veld leeg als je de gegevens niet automatisch wilt laten verwijderen.",
  
    "edit.campaignMonitor.nameField": "Adressering",  
    "edit.campaignMonitor.nameField.helpText": "Welk veld bevat de geregistreerde naam?",  
    "edit.checkbox.checked.helpText": "Standaard de checkbox aanvinken voor de bezoeker",  
    "edit.checked": "Aangevinkt",  
    "edit.close": "Sluiten",
    "edit.consent.consentText": "Toestemming",
    "edit.consent.consentText.helpText": "Beschrijf waar de bezoeker toestemming voor moet geven.",
    "edit.consent.linkPage.helpText": "Selecteer pagina waar aanvullende informatie op staat",
    "edit.consent.linkText": "Informatie pagina",
    "edit.consent.linkText.helpText": "Voer de link-tekst in",
    "edit.defaultText": "Standaard-tekst", 
    "edit.defaultText.helpText": "Bijvoorbeeld \" Selecteer...\" - Als deze leeg is, verschijnt er geen standaardtekst", 
    "edit.edit": "Wijzigen",
    "edit.email.allowMultiple": "Sta meerdere e-mails toe",
    "edit.email.allowMultiple.helpText": "Vink hier aan als bezoekers meerdere e-mailadressen kunnen invoeren.",
    "edit.errorMessage": "Foutmelding",
    "edit.errorMessage.helpText": "Het bericht dat aan gebruikers wordt getoond als de ingevoerde gegevens niet geldig zijn", 
    "edit.header.text.helpText": "De tekst die als titel moet worden weergegeven",
    "edit.helpText": "Helptekst",  
    "edit.helpText.helpText": "Toelichtng om de bezoeker extra informatie te geven", 
    "edit.image.choose": "Kies afbeelding",
    "edit.image.choose.helpText": "Klik hieronder om een afbeelding te selecteren",
    "edit.image.caption": "Onderschrift",
    "edit.image.caption.helpText": "De tekst die in de afbeelding moet worden weergegeven",
    "edit.label": "Tekst",  
    "edit.label.helpText": "De tekst die wordt weergegeven aan de bezoekers", 
    "edit.link.text": "Tekst",
    "edit.link.text.helpText": "De tekst moet als een link worden weergegeven",
    "edit.link.target": "Bestemming",
    "edit.link.target.helpText": "Selecteer de pagina waarnaar u wilt linken",
    "edit.link.select": "Selecteer...",
    "edit.link.openInNewWindow": "Open in een nieuw venster/tabblad",
    "edit.link.openInNewWindow.helpText": "Vink aan als je wilt dat de pagina opent in een nieuw venster/tabblad",
    "edit.mandatory": "Verplicht", 
    "edit.mandatory.helpText": "Vink aan als het veld verplicht is", 
    "edit.maxLength": "Maximaal aantal tekens",
    "edit.maxLength.helpText": "Maximaal aantal toegestane tekens in dit veld. (0 = onbeperkt)",
    "edit.memberInfo.helpText": "Dit is een onzichtbaar veld. Dit controleert of een member is ingelogd. Wanneer dit veld aan het formulier is toegevoegd, worden namen en e-mailadressen automatisch opgeslagen voor ingelogde leden.",
    "edit.name": "Naam",  
    "edit.name.helpText": "Naam moet uniek zijn",
    "edit.number.minimum": "Minimum",
    "edit.number.minimum.helpText": "Het laagste toegestane aantal",
    "edit.number.maximum": "Maximum",
    "edit.number.maximum.helpText": "Het hoogste toegestane aantal",
    "edit.ok": "Opslaan",
    "edit.options": "Opties",
    "edit.options.add": "Voeg een optie toe",  
    "edit.options.helpText": "Voeg de opties toe waaruit de bezoekers kunnen kiezen",
    "edit.options.selected": "Geselecteerd",  
    "edit.placeholder": "Placeholder",  
    "edit.placeholder.helpText": "Standaard tekst dat wordt getoond in de tekstbox. Als bezoeker er in typt, verdwijnt de tekst.", 
    "edit.renameWarning": "Als je een bestaand veld hernoemt, dan kun je de door bezoekers ingevulde gegevens van dit veld niet meer raadplegen.", 
    "edit.selectbox.multiSelect": "Toestaan meerdere te selecteren",
    "edit.selectbox.multiSelect.helpText": "Vink hier aan als bezoekers meerdere opties mogen kiezen", 
    "edit.selectbox.size": "Aantal weer te geven opties",
    "edit.selectbox.size.all": "Alle beschikbare opties", 
    "edit.selectbox.size.helpText": "Er verschijnt een schuifbalk als je een getal selecteert dat lager is dan het aantal beschikbare opties.", 
    "edit.submitButton.label": "Knop tekst",
    "edit.submitButton.label.helpText": "De tekst die op de knop wordt weergegeven. Bijv: \"Opslaan\" of \"Verzenden\"",
    "edit.text": "Tekst",
    "edit.textParagraph.text.helpText": "De tekst die in het tekstgedeelte moet worden weergegeven.",
    "edit.upload.allowedFileTypes": "Toegestane bestandstypen",
    "edit.upload.allowedFileTypes.helpText": "Bijv. \"JPG, PNG, GIF\"",
    "edit.upload.maxSize": "Max bestandsgrootte (KB)",
    "edit.upload.maxSize.helpText": "0 = onbeperkt",
  
    "common.clickToExpand": "Klik om te openen"
}